const workExperiences = [
  {
    company: "Dotmatics",
    companyLink: "https://www.dotmatics.com/",
    position: "Software Engineer",
    location: "Boston, MA",
    startDate: "Oct 2024",
    endDate: "Present",
    responsibilities:
      "As a Software Engineer at Dotmatics, I engineered full-stack features for Luma's Registration module, supporting single-compound and batch registration workflows for scientists to log, validate, and uniquely identify chemical and biological entities. I built record submission and tracking systems using React, TypeScript, and Node.js, developed and consumed RESTful APIs backed by PostgreSQL achieving a 25% reduction in query times, and contributed to event-driven backend services using Kafka, Scala, and Databricks for high-volume scientific data pipelines.",
    technologies: [
      "react",
      "typescript",
      "nodejs",
      "postgres",
      "kafka",
      "scala",
      "databricks",
      "jest",
      "docker",
      "kubernetes",
    ],
    logoName: "dotmaticsLogo",
  },
  {
    company: "Dayforce",
    companyLink: "https://www.dayforce.com/",
    position: "Software Engineer Intern",
    location: "Toronto, ON",
    startDate: "Sept 2023",
    endDate: "Apr 2024",
    responsibilities:
      "As a Software Engineer Intern at Dayforce, I developed features for the Benefits services enabling employees to efficiently manage their benefits, generating $1M in revenue. I refactored React frontend features using TypeScript and Redux for the Benefits Enrollment MFE with Jest integration testing, and revamped backend microservices using C# and .NET for efficient SQL querying, achieving a 10% increase in microservice throughput.",
    technologies: ["react", "typescript", "redux", "jest", "lint", "dotnet", "csharp", "mysql"],
    logoName: "dayforceLogo",
  },
  {
    company: "Tesla",
    companyLink: "https://www.tesla.com/",
    position: "Software Engineer Intern",
    location: "Fremont, CA",
    startDate: "Jan 2022",
    endDate: "Dec 2022",
    responsibilities:
      "As a Software Engineer Intern at Tesla, I developed a gamification system for Tesla service centers to automate vehicle repair and maintenance workflows, resulting in a 13% increase in overall productivity. I designed and deployed a full-stack dashboard using React, TypeScript, and Node.js containerized with Docker, and streamlined the Service Center Application enabling technicians to manage inventory, appointments, and client data using Angular and .NET microservices backed by PostgreSQL.",
    technologies: [
      "dotnet",
      "react",
      "typescript",
      "nodejs",
      "docker",
      "angular",
      "materialui",
      "semanticui",
      "ngxtranslate",
      "postgres",
    ],
    logoName: "teslaMotorsLogo",
  },
  {
    company: "Caliber Communications",
    companyLink: "https://calibercommunications.ca/",
    position: "Full Stack Developer Intern",
    location: "Stoney Creek, ON",
    startDate: "Sept 2021",
    endDate: "Dec 2021",
    responsibilities:
      "As a Full Stack Developer Intern at Caliber Communications, I optimized the workflow efficiency of security application users by 15% through the development of personalized dashboard interfaces with real-time data streams via WebSocket. I engineered backend microservices with Node.js, Express.js, and Knex, implemented automated PostgreSQL scripts to purge 3.5TB of obsolete data, and deployed a secure and scalable security reporting system leveraging containerization, traffic routing, and SSL termination.",
    technologies: [
      "angular",
      "rxjs",
      "express",
      "knex",
      "postgres",
      "docker",
      "nginx",
    ],
    logoName: "caliberCommunicationsLogo",
  },
  {
    company: "Evenica",
    companyLink: "https://www.evenica.com/",
    position: "Web Developer Intern",
    location: "Burlington, ON",
    startDate: "May 2021",
    endDate: "Aug 2021",
    responsibilities:
      "At Evenica, I revamped the e-commerce UI, enhancing accessibility and reducing the frontend codebase by 35% through the development of a web component library enabling plug-and-play configuration and client business customization features. I also implemented a secure payment terminal to establish a resilient payment pipeline, ensuring the integrity of client payment data through the integration of Adyen's payment API.",
    technologies: ["dynamics365", "react", "dotnet", "adyen"],
    logoName: "evenicaLogo",
  },
];

export default workExperiences;
